In [7]:
import pandas as pd
import numpy as np

In [2]:
### df_test loaded from patch0full.py input (plot, train)

df_test = pd.read_hdf('results/checkpatch0/df_test.h5')

In [5]:
print(len(df_test))
df_test.head()

169652

,pmdec,pmra,dec,ra,b-r,g,rotra,rotdec,rotpmra,rotpmdec,stream,region_label,nn_score
51,-11.140583,1.471265,19.514811,140.278625,0.757143,13.918437,11.336031,-8.681488,2.581717,-10.936725,False,0,0.272384
67,-12.605638,-2.525475,18.907951,138.661499,2.270811,18.813795,9.854070,-9.428756,-1.418662,-12.777618,False,1,0.276202
90,-9.874997,-9.321015,19.034031,137.639404,2.259640,20.231148,8.867104,-9.383096,-8.517515,-10.575861,False,0,0.336741
91,-9.793378,0.008021,19.475325,139.391418,1.370239,17.690496,10.497677,-8.801635,0.918632,-9.750201,False,0,0.285527
119,-10.103176,1.568011,18.884327,139.767700,0.653490,13.585656,10.912607,-9.356350,2.533377,-9.905293,False,0,0.264204

In [ ]:
# def fiducial_selections(df, do_kmeans=True, k=2): 
#     # CWOLA Stellar Stream fiducial cuts https://arxiv.org/pdf/2305.03761
#     df = df[df['g'] < 20.2] # ensures uniform acceptance by Gaia satellite
#     df = df[(np.abs(df['rotpmdec']) > 2) | (np.abs(df['rotpmra']) > 2)] # remove distant stars concentrated near zero proper motion, not equally distributed throughout patch
#     df = df[(df['b-r'] >= 0.5) & (df['b-r'] <=1 )] # isolates old and low-metallicity stellar streams in color space

#     # Kmeans clustering
#     if do_kmeans:

#     return df

In [4]:
def fiducial_selections(df): 
    # CWOLA Stellar Stream fiducial cuts https://arxiv.org/pdf/2305.03761
    df = df[df['g'] < 20.2] # ensures uniform acceptance by Gaia satellite
    df = df[(np.abs(df['rotpmdec']) > 2) | (np.abs(df['rotpmra']) > 2)] # remove distant stars concentrated near zero proper motion, not equally distributed throughout patch
    df = df[(df['b-r'] >= 0.5) & (df['b-r'] <=1 )] # isolates old and low-metallicity stellar streams in color space

    return df

In [9]:
df_updated = fiducial_selections(df_test)
len(df_updated)

44351

In [19]:
df_ranked = df_updated.sort_values(by='nn_score', ascending=False)
df_top_250 = df_ranked[:250]
df_top_250.head()

,pmdec,pmra,dec,ra,b-r,g,rotra,rotdec,rotpmra,rotpmdec,stream,region_label,nn_score
452955,-12.146438,-4.997474,26.700659,141.785767,0.557089,18.935139,11.955947,-1.389485,-3.611030,-12.628189,False,1,0.853501
453492,-13.027168,-5.187256,27.205256,141.965454,0.559967,19.468956,12.058459,-0.870095,-3.681652,-13.529973,True,1,0.847186
560089,-12.799329,-3.864178,29.260689,143.086975,0.569561,19.028669,12.797996,1.287238,-2.271496,-13.175545,True,1,0.798845
543895,-12.961712,-5.075985,28.698730,142.877136,0.610531,18.876196,12.683941,0.707163,-3.477842,-13.478732,True,1,0.798588
605496,-12.449367,-5.208322,30.384840,144.222046,0.574530,18.707365,13.632690,2.527183,-3.526454,-13.026030,True,1,0.792569

In [21]:
purity = len(df_top_250[df_top_250['stream']==True]) / len(df_top_250)
print(f'{purity * 100} %')

77.2 %

In [23]:
completeness = len(df_top_250[df_top_250['stream']==True])/len(df_test[df_test['stream']==True])
print(f'{completeness * 100} %')

53.02197802197802 %

In [16]:
### try k-means clustering

# import matplotlib.pyplot as plt
# from sklearn.cluster import KMeans
# from sklearn.preprocessing import StandardScaler

# pm_values = df_updated['rotpmdec'].to_numpy()

# scaler = StandardScaler()
# scaled_pm = scaler.fit_transform(pm_values)

# kmeans = KMeans(init='random', n_clusters=2, n_init=10, max_iter=200, random_state=15)
# kmeans.fit(scaled_pm)

# kmeans.labels_[:10]